
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cs.cloudplus.io
  resources:
  - aliyuncks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cs.cloudplus.io
  resources:
  - aliyuncks/status
  verbs:
  - get
  - patch
  - update
